name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mongodb:
        - '7.0'
        mongo_driver:
        - mongodb6
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb }}
        ports:
        - 27017:27017
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      # Skip post-install to avoid malicious scripts stealing PAT
      run: npm install --ignore-script
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Post-install
      run: npm rebuild && npm run prepare --if-present
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
      env:
        MONGO_DRIVER: ${{ matrix.mongo_driver }}
    - name: Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: ./release.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # A silly job just so we can mark this as the required check for PRs
  # instead of maintaining the full list of matrix jobs
  success:
    needs:
    - build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Success
      run: echo "Success"
